# Generated by Django 5.2.3 on 2025-06-22 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heart_flow_app', '0012_patientprofile_medical_reference_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('linked_patient', models.ForeignKey(blank=True, help_text='Link to actual PatientProfile once created', null=True, on_delete=django.db.models.deletion.SET_NULL, to='heart_flow_app.patientprofile')),
                ('referred_by', models.ForeignKey(limit_choices_to={'role': 'General Practitioner'}, on_delete=django.db.models.deletion.CASCADE, related_name='referred_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
