# Generated by Django 5.2.3 on 2025-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0002_patientreferral_referred_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
