# Generated by Django 5.2.3 on 2025-06-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0003_patientreferral_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_referral_audios/'),
        ),
        migrations.AddField(
            model_name='patientreferral',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreferral',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
