# Generated by Django 5.2.3 on 2025-06-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0004_patientreferral_audio_file_patientreferral_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='referral_pdf',
            field=models.FileField(blank=True, null=True, upload_to='referral_pdf/'),
        ),
    ]
