# Generated by Django 5.2.3 on 2025-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0005_patientreferral_referral_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
