# Generated by Django 5.2.3 on 2025-06-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0006_patientreferral_doctor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreferral',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Ongoing', 'Ongoing')], default='Pending', max_length=20),
        ),
    ]
