# Generated by Django 5.2.3 on 2025-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0007_alter_patientreferral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='medical_reference_no',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
