# Generated by Django 5.2.3 on 2025-06-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0008_patientreferral_medical_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
