# Generated by Django 5.2.3 on 2025-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_app', '0009_patientreferral_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='patient_reports',
            field=models.FileField(blank=True, null=True, upload_to='patients_medical_reports/'),
        ),
    ]
