# Generated by Django 5.2.3 on 2025-06-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0010_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='heart_flow_app.allergy'),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('description', models.TextField()),
                ('medication_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_from', to='heart_flow_app.medication')),
                ('medication_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_to', to='heart_flow_app.medication')),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='medications',
            field=models.ManyToManyField(to='heart_flow_app.medication'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_flow_app.patientprofile')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_flow_app.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='heart_flow_app.prescription')),
            ],
        ),
    ]
