# Generated by Django 5.2.3 on 2025-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0011_allergy_medication_profileuser_user_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='medical_reference_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
