# Generated by Django 5.2.3 on 2025-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0013_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='medical_files/'),
        ),
    ]
