# Generated by Django 5.2.3 on 2025-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0014_appointment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='id_records',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
