# Generated by Django 5.2.3 on 2025-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_flow_app', '0016_alter_patientprofile_id_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='joining_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
