# Generated by Django 5.2.3 on 2025-06-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_diagnostictestresult'),
        ('heart_flow_app', '0017_profileuser_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='diagnostic_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_notifications', to='admin_app.diagnosticappointment'),
        ),
    ]
