# Generated by Django 5.2.3 on 2025-06-23 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heart_flow_app', '0013_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SonographyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='sonography_reports/')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heart_flow_app.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'Cardiologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='referring_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sonographer', models.ForeignKey(limit_choices_to={'role': 'Sonographer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sonographer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
