# Generated by Django 5.2.3 on 2025-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonographyreferral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
