# Generated by Django 5.2.3 on 2025-06-28 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heart_flow_app', '0016_alter_patientprofile_id_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Blood Test', 'Blood Test'), ('ECG', 'ECG'), ('Echocardiogram', 'Echocardiogram'), ('TMT', 'TMT'), ('Holter Monitor', 'Holter Monitor')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(limit_choices_to={'role__in': ['Nurse', 'Sonographer']}, on_delete=django.db.models.deletion.CASCADE, related_name='test_appointments', to=settings.AUTH_USER_MODEL)),
                ('booked_by', models.ForeignKey(limit_choices_to={'role': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='booked_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_appointments', to='heart_flow_app.patientprofile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.diagnostictest')),
            ],
        ),
    ]
