# Generated by Django 5.2.3 on 2025-06-29 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_summary', models.TextField()),
                ('attached_report', models.FileField(blank=True, null=True, upload_to='diagnostic_reports/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='admin_app.diagnosticappointment')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Nurse', 'Sonographer', 'IT Staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
